language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

notifications:
  email: false

sudo: false

cache:
  directories:
  - $HOME/.m2

script:
  - ./gradlew assembleDebug

env:
  global:
    secure: "QLwzAznNExh47/1lCGEcem3wmEF+Z56ZkM2PG3BeLfP+BuGe8K1hScqmwhWEEO1thrqd24dZH8PsYwfHGfy7bRphql+5sZBEP131126Vl51CjUpudcFKI1OzwAnLb5HlV4PFJvBvOCtjP3572OleJds571nFckvp8qL76R+vsn27la8E7iomyWH2aCv+DI4T4Zb0kYaTp3wq/K/933qIvBjgA+WiNpWRYpIdUO8ibCwLni6qmTCtJWt+C1+vTvkRI1FLYyxAM13HjwEgWN4c+NlPHbMg8IY1pR53sfNnTIPXIwGL5GcrH8u8xmxMJwCeC7l9IDFgpPl2+1vYJ3S9yiPLdg/e1zNsa4hajhkv9hjkCBR3dCqGLk2alrYxDw8wTB9lATXS61aSeHbIrcQM+IdBOmQj2ZPT18brEqS7Se5lb3T9Ow+MN5xecmiF7hdtXbdJuomUL7cbtUDszq0RLSfmCynLZDid1a1tglDNTC2xWFTZyrB/ToiWXJhv0JAksHHFrVUUuZyCZDD65svIDMOhebZRipQ3VnddinCWw7khK9q5hcHKIeciSY6mJG5VsUNaszLvQ9OqR/unjsox/xSQLiWl0mO6PXgbrstd/8OvXYyd39p3N8ghtzQD/P11PqDfxrkgBDdLfgKpI5xqIkg+ccIaEOmXrEKkv2q7/Ss="
    secure: "UB5HOojIlOV6TkSbLh4g5m1Aan8Lqg0GdjZjtb9LXdiSzeiskPGbsVDZzN9k29KOyN64rWIcQL1I2YWwHv1snjoIVSZ4Eec/FwA+b2J/k7DdHWpuR9lSDZjbF6HMzxCx03ZhXksb27TlQ4wpwWbAc5JB5Zs3mv1lNJJHqB8G9/ms31BkpdO2dx4fde6RhruqfZQ1TY1TGXTHw6g27/jLYAJTM33/M+LkT8FDfEOOM8que2DGGbscJjNVRh+cACyRaG3jRhp0j4svHgkFokOjEc2IO9oRMucgTzZEsOeQmw9SX0ty0T2LQ1yiKDeYXH80xYnVpiE0pmmGzEQNO9DdGSAQ2IXt2ww0/ZZ8wG9nK7FvYJH6yjspyJ0tpYH+v8xFMlMoIP+/D8FTNyBV+GNpRof9ObMq5g1kwwV1t8WEDjCYQTkpB+ubTRj/NI9Zzw1a4uJNEYUbX3JES639ArO2puB+o19qlCevL1up1XJIDZR7K8weoUhusNP7D8a8BFuj77ZOeOSCzOBNZUJQgVhpJXj+BS4WMUld3juSdYfYcw6EX59Y0z4SQhfYdrIWBLGbIz68ON+xu6AQdeCuGIU+8ZnW2HuPqIdzjD2Qy4avEA6s98jV7XTp4EW+Tg+EtQJHSytXupQPCrdXFYVBZWiIPneZU88CiCJHGpNruyJAEqs="
